### PR TITLE
Fix for oF 0.9.2

### PR DESCRIPTION
**Pull request by mruegenberg**
I updated the code to work with the current version of oF.

### CODE REVIEW

**Comment by prisonerjohn** [comment]
Hey, thanks for this but I've already got these changes and a bunch more in the feature-0.9.0 branch: https://github.com/prisonerjohn/ofxVolumetrics/tree/feature-0.9.0

**Comment by mruegenberg** [comment]
oh, ok, great :-) 
I just pulled the master branch and wrongly assumed that would be the current version.

I think it might be a good idea to merge that branch to master, since the official oF release as been 0.9.\* for several months now.

**Comment by prisonerjohn** [comment]
Definitely, but there are some issues with the fixed pipeline that I was trying to figure out. It looks like it might just be broken, which is why I'm hesitating. See https://github.com/openframeworks/openFrameworks/pull/4841

**Comment by mruegenberg** [comment]
So, as long as I use the programmable pipeline, things should be ok with just using this branch, right?

**Comment by prisonerjohn** [comment]
Yes, that's what I'm using and it's all good.

## 

Elie Zananiri

514.436.7678
@prisonerjohn

**Pull request closed without merging**
